services:
  backend:
    build: .
    image: script-runner:latest
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/data.db
      - SCRIPTS_DIR=/app/scripts
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
